# Generated by Django 5.2.1 on 2025-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cquser",
            name="last_email_change",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dernier changement d'email"),
        ),
        migrations.AddField(
            model_name="cquser",
            name="last_password_change",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dernier changement de mot de passe"),
        ),
        migrations.AddField(
            model_name="cquser",
            name="last_trigram_change",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dernier changement de trigram"),
        ),
    ]
