# Generated by Django 5.2.1 on 2025-08-04 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("pointed_date", models.DateField(blank=True, null=True)),
                ("current_pointed_date", models.DateField(blank=True, null=True)),
                (
                    "current_pointed_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "average_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The average interest that is expected for",
                        max_digits=8,
                    ),
                ),
                (
                    "ledger_analysis",
                    models.BooleanField(
                        default=True,
                        help_text="If the account is include in the ledger analysis",
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Open", "Ouvert"), ("Close", "Fermé")],
                        default="Open",
                        max_length=15,
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="After the closed date it is not possibile to add transaction or modify this account",
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[("CE", "CE"), ("CA", "CA"), ("GMF", "GMF")],
                        default="CA",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(default="Current", editable=False, max_length=15),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseOutgoings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_integrated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Monthly", "monthly"),
                            ("Half-yearly", "half-yearly"),
                            ("Quaterly", "quaterly"),
                            ("Yearly", "yearly"),
                        ],
                        default="Monthly",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "outgoings_type",
                    models.CharField(default="Expense", editable=False, max_length=15),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_transaction", models.DateTimeField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "date_pointed",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("updatable", models.BooleanField(default=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Expense", "expense"),
                            ("Income", "income"),
                            ("Transfer", "transfer"),
                            ("Outgoings", "outgoings"),
                        ],
                        db_index=True,
                        default="Expense",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FundDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_name", models.CharField(max_length=50)),
                (
                    "prct",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("fund_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FundHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_value", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="IncomeOutgoings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_integrated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Monthly", "monthly"),
                            ("Half-yearly", "half-yearly"),
                            ("Quaterly", "quaterly"),
                            ("Yearly", "yearly"),
                        ],
                        default="Monthly",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "outgoings_type",
                    models.CharField(default="Income", editable=False, max_length=15),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncomeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_transaction", models.DateTimeField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "date_pointed",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("updatable", models.BooleanField(default=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Expense", "expense"),
                            ("Income", "income"),
                            ("Transfer", "transfer"),
                            ("Outgoings", "outgoings"),
                        ],
                        db_index=True,
                        default="Expense",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestmentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("pointed_date", models.DateField(blank=True, null=True)),
                ("current_pointed_date", models.DateField(blank=True, null=True)),
                (
                    "current_pointed_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "average_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The average interest that is expected for",
                        max_digits=8,
                    ),
                ),
                (
                    "ledger_analysis",
                    models.BooleanField(
                        default=True,
                        help_text="If the account is include in the ledger analysis",
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("Open", "Ouvert"), ("Close", "Fermé")],
                        default="Open",
                        max_length=15,
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="After the closed date it is not possibile to add transaction or modify this account",
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[("CE", "CE"), ("CA", "CA"), ("GMF", "GMF")],
                        default="CA",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(
                        default="Investment", editable=False, max_length=15
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestmentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="Designation"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("Bond", "Bond"),
                            ("ETF", "ETF"),
                            ("Crypto", "Crypto"),
                            ("Other", "Other"),
                        ],
                        default="Stock",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Cours ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Closed", "closed"), ("Open", "open")],
                        default="Open",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferOutgoings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_integrated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Monthly", "monthly"),
                            ("Half-yearly", "half-yearly"),
                            ("Quaterly", "quaterly"),
                            ("Yearly", "yearly"),
                        ],
                        default="Monthly",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "outgoings_type",
                    models.CharField(default="Transfer", editable=False, max_length=15),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransferTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_transaction", models.DateTimeField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "date_pointed",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("updatable", models.BooleanField(default=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Expense", "expense"),
                            ("Income", "income"),
                            ("Transfer", "transfer"),
                            ("Outgoings", "outgoings"),
                        ],
                        db_index=True,
                        default="Expense",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
