# Generated by Django 5.2.1 on 2025-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "name",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
