# Generated by Django 5.2.1 on 2025-07-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comptas", "0002_wallet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
