# Generated by Django 5.2.1 on 2025-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptas", "0003_delete_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentaccount",
            name="state",
            field=models.CharField(choices=[("open", "Ouvert"), ("close", "Fermé")], default="open", max_length=15),
        ),
        migrations.AddField(
            model_name="investmentaccount",
            name="state",
            field=models.CharField(choices=[("open", "Ouvert"), ("close", "Fermé")], default="open", max_length=15),
        ),
        migrations.AlterField(
            model_name="currentaccount",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="currentaccount",
            name="current_pointed_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="currentaccount",
            name="current_pointed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currentaccount",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="currentaccount",
            name="pointed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="current_pointed_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="current_pointed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="pointed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
