# Generated by Django 5.2.1 on 2025-07-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptas", "0004_currentaccount_state_investmentaccount_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentaccount",
            name="state",
            field=models.CharField(choices=[("Open", "Ouvert"), ("Close", "Fermé")], default="Open", max_length=15),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="state",
            field=models.CharField(choices=[("Open", "Ouvert"), ("Close", "Fermé")], default="Open", max_length=15),
        ),
        migrations.CreateModel(
            name="InvestmentAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("designation", models.CharField(max_length=100, verbose_name="Designation")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Stock", "Stock"),
                            ("Bond", "Bond"),
                            ("ETF", "ETF"),
                            ("Crypto", "Crypto"),
                            ("Other", "Other"),
                        ],
                        default="Stock",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Quantity")),
                (
                    "price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Current price"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="comptas.investmentaccount",
                    ),
                ),
            ],
        ),
    ]
