# Generated by Django 5.2.1 on 2025-08-04 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description/Objectif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Séances réalisées"
                    ),
                ),
                (
                    "associated_routes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parcours associés"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapitre",
                "verbose_name_plural": "Chapitres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Acte 1"),
                            (2, "Acte 2"),
                            (3, "Acte 3"),
                            (4, "Acte 4"),
                            (5, "Acte 5"),
                            (6, "Acte 6"),
                            (7, "Acte 7"),
                        ],
                        verbose_name="Numéro",
                    ),
                ),
                ("short", models.TextField(blank=True, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acts",
                        to="chapters.chapter",
                        verbose_name="Chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acte",
                "verbose_name_plural": "Actes",
                "ordering": ["chapter", "number"],
                "unique_together": {("chapter", "number")},
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Scène 1"), (2, "Scène 2"), (3, "Scène 3")],
                        verbose_name="Numéro",
                    ),
                ),
                ("short", models.TextField(blank=True, verbose_name="Titre")),
                (
                    "instructions",
                    models.TextField(
                        help_text="Format: => Instruction 1\n=> Instruction 2",
                        verbose_name="Instructions",
                    ),
                ),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="chapters.act",
                        verbose_name="Acte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scène",
                "verbose_name_plural": "Scènes",
                "ordering": ["act", "number"],
                "unique_together": {("act", "number")},
            },
        ),
    ]
