# Generated by Django 5.2.1 on 2025-05-31 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("todo", "À faire"),
                            ("in_progress", "En cours"),
                            ("done", "Terminé"),
                            ("report", "Reporté"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                ("description", models.TextField()),
                ("appointment", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("01-organisation", "Organisation"),
                            ("02-compta", "Compta"),
                            ("03-achat", "Achats"),
                            ("04-sport", "Sport"),
                            ("05-sante", "Santé"),
                            ("06-contact", "Contact"),
                            ("07-informatique", "Informatique"),
                            ("08-menage", "Menage"),
                            ("09-jardin", "Jardin"),
                            ("10-doudou", "Doudou"),
                            ("11-bricoles", "Bricoles"),
                            ("12-couture", "Couture"),
                            ("13-loisirs", "Loisirs"),
                        ],
                        default="01-organisation",
                        max_length=20,
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        choices=[
                            ("SLB", "Sylvie"),
                            ("JCB", "Jean-Christophe"),
                            ("LAU", "Laurine"),
                            ("THO", "Thomas"),
                            ("ODI", "Odile"),
                        ],
                        default="SLB",
                        max_length=20,
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[("cantin", "Cantin"), ("chm", "CHM"), ("genese", "Genèse"), ("partout", "Partout")],
                        default="partout",
                        max_length=20,
                    ),
                ),
                (
                    "periodic",
                    models.CharField(
                        choices=[
                            ("01-none", "une seule fois"),
                            ("02-everyday", "Tous les jours"),
                            ("03-every2days", "Tous les 2 jours"),
                            ("04-every3days", "Tous les 3 jours"),
                            ("05-every4days", "Tous les 4 jours"),
                            ("06-every5days", "Tous les 5 jours"),
                            ("07-everyweek", "Toutes les semaines"),
                            ("08-every10days", "Tous les 10 jours"),
                            ("09-every2weeks", "Toutes les 2 semaines"),
                            ("10-everymonth", "Tous les mois"),
                            ("11-every6weeks", "Toutes les 6 semaines"),
                            ("12-every2months", "Tous les 2 mois"),
                            ("13-every3months", "Tous les 3 mois"),
                            ("14-every4months", "Tous les 4 mois"),
                            ("15-every6months", "Tous les 6 mois"),
                            ("16-everyyear", "Tous les ans"),
                        ],
                        default="partout",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("6-verylow", "Très faible"),
                            ("5-low", "Faible"),
                            ("4-normal", "Normale"),
                            ("3-medium", "Moyenne"),
                            ("2-high", "Élevée"),
                            ("1-highest", "Trés élevée"),
                        ],
                        default="01-none",
                        max_length=20,
                    ),
                ),
                ("done", models.DateField()),
                ("note", models.TextField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
