# Generated by Django 5.2.1 on 2025-06-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="done",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="who",
            field=models.CharField(
                choices=[
                    ("SLB", "Sylvie"),
                    ("JCB", "Jean-Christophe"),
                    ("LAU", "Laurine"),
                    ("THO", "Thomas"),
                    ("ODI", "Odile"),
                    ("MAM", "Maman"),
                    ("PAP", "Papa"),
                ],
                default="SLB",
                max_length=20,
            ),
        ),
    ]
