# Generated by Django 5.2.1 on 2025-07-18 14:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_todo_date_remove_todo_done_todo_done_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 19)),
        ),
        migrations.AlterField(
            model_name="todo",
            name="who",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
