# Generated by Django 5.2.1 on 2025-06-16 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_todo_done_alter_todo_who"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="date",
            new_name="current_date",
        ),
        migrations.AddField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
