# Generated by Django 5.2.1 on 2025-07-19 06:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_todo_planned_date_alter_todo_who"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 20)),
        ),
    ]
