# Generated by Django 5.2.1 on 2025-06-17 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_rename_date_todo_current_date_todo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="duration",
            field=models.IntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(800),
                ],
            ),
        ),
    ]
