# Generated by Django 5.2.1 on 2025-06-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_todo_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="current_date",
        ),
        migrations.AddField(
            model_name="todo",
            name="lest_execute_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
