# Generated by Django 5.2.1 on 2025-07-29 07:10

import datetime

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_todo_planned_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 30)),
        ),
        migrations.RemoveField(
            model_name="todo",
            name="who",
        ),
        migrations.AddField(
            model_name="todo",
            name="who",
            field=models.ManyToManyField(blank=True, related_name="todos", to=settings.AUTH_USER_MODEL),
        ),
    ]
