# Generated by Django 5.2.1 on 2025-06-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_todo_current_date_todo_lest_execute_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="done",
            new_name="done_date",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="lest_execute_date",
            new_name="last_execute_date",
        ),
    ]
