# Generated by Django 5.2.1 on 2025-06-24 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_rename_done_todo_done_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="last_execute_date",
            new_name="report_date",
        ),
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 25, 12, 38, 22, 683774, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
