# Generated by Django 5.2.1 on 2025-06-25 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_rename_last_execute_date_todo_report_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 6, 26)),
        ),
    ]
