# Generated by Django 5.2.1 on 2025-06-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_todo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 6, 29)),
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[
                    ("6-verylow", "Très faible"),
                    ("5-low", "Faible"),
                    ("4-normal", "Normale"),
                    ("3-medium", "Moyenne"),
                    ("2-high", "Élevée"),
                    ("1-highest", "Trés élevée"),
                ],
                default="4-normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="state",
            field=models.CharField(
                choices=[
                    ("todo", "À faire"),
                    ("in_progress", "En cours"),
                    ("done", "Terminé"),
                    ("report", "Reporté"),
                    ("cancel", "Annulé"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
