# Generated by Django 5.2.1 on 2025-06-30 22:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_todo_planned_date_alter_todo_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 1)),
        ),
    ]
