# Generated by Django 5.2.1 on 2025-07-01 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_todo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="appointment",
            field=models.CharField(
                blank=True,
                choices=[("rdv", "rdv"), ("birthday", "anniversaire"), ("festival", "fête")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 2)),
        ),
    ]
