# Generated by Django 5.2.1 on 2025-07-03 08:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_todo_appointment_alter_todo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="appointment",
            field=models.CharField(
                blank=True,
                choices=[("rdv", "Rendez-vous"), ("birthday", "Anniversaire"), ("festival", "Fête")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
    ]
