# Generated by Django 5.2.1 on 2025-07-11 16:45

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_todo_appointment_alter_todo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2025, 7, 12)),
        ),
        migrations.CreateModel(
            name="ColorParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("6-verylow", "Très faible"),
                            ("5-low", "Faible"),
                            ("4-normal", "Normale"),
                            ("3-medium", "Moyenne"),
                            ("2-high", "Élevée"),
                            ("1-highest", "Trés élevée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("01-none", "une seule fois"),
                            ("02-everyday", "Tous les jours"),
                            ("03-every2days", "Tous les 2 jours"),
                            ("04-every3days", "Tous les 3 jours"),
                            ("05-every4days", "Tous les 4 jours"),
                            ("06-every5days", "Tous les 5 jours"),
                            ("07-everyweek", "Toutes les semaines"),
                            ("08-every10days", "Tous les 10 jours"),
                            ("09-every2weeks", "Toutes les 2 semaines"),
                            ("10-everymonth", "Tous les mois"),
                            ("11-every6weeks", "Toutes les 6 semaines"),
                            ("12-every2months", "Tous les 2 mois"),
                            ("13-every3months", "Tous les 3 mois"),
                            ("14-every4months", "Tous les 4 mois"),
                            ("15-every6months", "Tous les 6 mois"),
                            ("16-everyyear", "Tous les ans"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("01-organisation", "Organisation"),
                            ("02-compta", "Compta"),
                            ("03-achat", "Achats"),
                            ("04-sport", "Sport"),
                            ("05-sante", "Santé"),
                            ("06-contact", "Contact"),
                            ("07-informatique", "Informatique"),
                            ("08-menage", "Menage"),
                            ("09-jardin", "Jardin"),
                            ("10-doudou", "Doudou"),
                            ("11-bricoles", "Bricoles"),
                            ("12-couture", "Couture"),
                            ("13-loisirs", "Loisirs"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[("cantin", "Cantin"), ("chm", "CHM"), ("genese", "Genèse"), ("partout", "Partout")],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entrez une couleur au format hexadécimal valide (ex: #1A2B3C).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("priority", "periodicity", "category", "place"), name="unique_color_combination"
                    )
                ],
            },
        ),
    ]
