# Generated by Django 5.2.1 on 2025-08-04 21:39

import secretbox.tools.date_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=secretbox.tools.date_tools.get_now_date,
                        help_text="Date à laquelle cette pensée a été écrite",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Le contenu de cette pensée"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this entry was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this entry was last modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pensée",
                "verbose_name_plural": "Pensées",
                "ordering": ["date"],
            },
        ),
    ]
