# Generated by Django 5.2.1 on 2025-06-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarylab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(default=datetime.datetime(2025, 6, 8, 10, 41, 11, 638273)),
        ),
    ]
