# Generated by Django 5.2.1 on 2025-08-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diarylab", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur qui a écrit cette pensée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_user_diaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="diaryentry",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_entry_per_user_per_date"
            ),
        ),
    ]
