# Generated by Django 5.2.1 on 2025-06-13 17:21

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarylab", "0002_alter_diaryentry_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="content",
            field=models.TextField(
                blank=True, help_text="The main content of the diary entry"
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this entry was created"
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 13, 17, 21, 34, 784458, tzinfo=datetime.timezone.utc
                ),
                help_text="Date when this diary entry was written",
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when this entry was last modified"
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this diary entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_user_diaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
