# Generated by Django 5.2.1 on 2025-06-14 16:48

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarylab", "0003_alter_diaryentry_content_alter_diaryentry_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 14, 16, 48, 46, 227941, tzinfo=datetime.timezone.utc),
                help_text="Date when this diary entry was written",
            ),
        ),
    ]
