# Generated by Django 5.2.1 on 2025-06-15 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import secretbox.tools.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "diarylab",
            "0003_alter_diaryentry_content_alter_diaryentry_created_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="content",
            field=models.TextField(blank=True, help_text="Le contenu de cette pensée"),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(
                default=secretbox.tools.models.get_now_date,
                help_text="Date à laquelle cette pensée a été écrite",
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur qui a écrit cette pensée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_user_diaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="diaryentry",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_entry_per_user_per_date"
            ),
        ),
    ]
