# Generated by Django 5.2.1 on 2025-06-14 19:36

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarylab", "0004_alter_diaryentry_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 14, 19, 36, 58, 259183, tzinfo=datetime.timezone.utc),
                help_text="Date when this diary entry was written",
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur qui a écrit cette pensée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_user_diaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="diaryentry",
            constraint=models.UniqueConstraint(fields=("user", "date"), name="unique_entry_per_user_per_date"),
        ),
    ]
