# Generated by Django 5.2.1 on 2025-06-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarylab", "0005_alter_diaryentry_date_alter_diaryentry_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="content",
            field=models.TextField(blank=True, help_text="Le contenu de cette pensée"),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 15, 9, 22, 13, 680378, tzinfo=datetime.timezone.utc),
                help_text="Date à laquelle cette pensée a été écrite",
            ),
        ),
    ]
