# Generated by Django 5.2.1 on 2025-06-15 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarylab", "0007_alter_diaryentry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 15, 17, 34, 30, 355087, tzinfo=datetime.timezone.utc),
                help_text="Date à laquelle cette pensée a été écrite",
            ),
        ),
    ]
