# Generated by Django 5.2.1 on 2025-08-07 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comptas", "0002_initial"),
        ("healths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="health",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_healths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mutuelle",
            name="income_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutuelle_income_transactions",
                to="comptas.incometransaction",
            ),
        ),
        migrations.AddField(
            model_name="health",
            name="mutuelle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutuelle",
                to="healths.mutuelle",
            ),
        ),
        migrations.AddField(
            model_name="secu",
            name="income_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secu_income_transactions",
                to="comptas.incometransaction",
            ),
        ),
        migrations.AddField(
            model_name="health",
            name="secu",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secu",
                to="healths.secu",
            ),
        ),
        migrations.AddIndex(
            model_name="health",
            index=models.Index(
                fields=["user", "date"], name="healths_hea_user_id_e042ad_idx"
            ),
        ),
    ]
