# Generated by Django 5.2.1 on 2025-08-04 21:39

import django.core.validators
import secretbox.tools.date_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sami",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=secretbox.tools.date_tools.get_now_date),
                ),
                ("weight", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bedtime",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 3",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "wakeup",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 3",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "nonstop",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "energy",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "naptime",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 4",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 2",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "reading",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 3",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "fruits",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 3",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "vegetables",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 2",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "meals",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "desserts",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "sugardrinks",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "nosugardrinks",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "homework",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "garden",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "outsidetime",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "endurancesport",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "yogasport",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "videogames",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "papergames",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "administrative",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "computer",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "youtube",
                    models.IntegerField(
                        default=0,
                        help_text="Saisir une valeur entre 0 et 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Sami",
                "verbose_name_plural": "Samis",
                "ordering": ["date"],
            },
        ),
    ]
