# Generated by Django 5.2.1 on 2025-06-14 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sami",
            name="date",
            field=models.DateField(default=datetime.datetime(2025, 6, 14, 16, 48, 46, 229974)),
        ),
    ]
