# Generated by Django 5.2.1 on 2025-06-15 20:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sami",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 15, 20, 38, 18, 495997, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
