# Generated by Django 5.2.1 on 2025-06-15 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0002_alter_sami_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sami",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 15, 20, 38, 31, 613853, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
