# Generated by Django 5.2.1 on 2025-06-15 21:07

from django.db import migrations, models

import secretbox.tools.models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0003_alter_sami_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sami",
            name="date",
            field=models.DateField(default=secretbox.tools.models.get_now_date),
        ),
    ]
