# Generated by Django 5.2.1 on 2025-06-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0003_alter_sami_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sami",
            name="date",
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 9, 22, 13, 684516)),
        ),
    ]
