# Generated by Django 5.2.1 on 2025-06-15 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0004_alter_sami_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sami",
            name="date",
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 17, 25, 13, 902159)),
        ),
    ]
