# Generated by Django 5.2.1 on 2025-06-30 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sami", "0004_alter_sami_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sami",
            name="Outsidetime",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="administrative",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="computer",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="desserts",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="endurancesport",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="fruits",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 3",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="garden",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="homework",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="meals",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="nosugardrinks",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="papergames",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="sugardrinks",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="vegetables",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 2",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="videogames",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="yogasport",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sami",
            name="youtube",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="bedtime",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 3",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="energy",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="naptime",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 4",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="nonstop",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 5",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="phone",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 2",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="reading",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 3",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="sami",
            name="wakeup",
            field=models.IntegerField(
                default=0,
                help_text="Saisir une valeur entre 0 et 3",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)],
            ),
        ),
    ]
