name: Quality Checks

on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Name of application'
        required: true
        default: 'SecretBox'
      page:
        description: 'Page to navigate to'
        required: true
        default: 'dashboard'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: "config.settings.prod"
  DEFAULT_FROM_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: 587
  EMAIL_USE_TLS: True
  EMAIL_HOST_USER: ${{ secrets.ADMIN_EMAIL }}
  EMAIL_HOST_PASSWORD: ${{ secrets.SENDGRID_API_KEY }}
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:

  build:
    runs-on: 
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      
      - name: Prepare environment
        run: |
          cp .env.example .env
      
  code-quality:
    needs: build
    runs-on: 
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Flake8
        run: |
          pip install uv
          uv add flake8
          uv add pylint
      - name: Run code quality checks
        run: |
          echo "Running code quality checks"
          uv run isort . --check --diff
          uv run black . --check
          uv run flake8 . --count --exit-zero --max-complexity=10 --statistics
      - name: Run pylint
        run: |
          uv run pylint $(git ls-files '*.py') --fail-under=9 --ignore=migrations, tests/output > tests/output/pylint.txt

 