name: Security Checks

on:
  workflow_dispatch:
      inputs:
      application:
        description: 'Name of application'
        required: true
        default: 'SecretBox'
      page:
        description: 'Page to navigate to'
        required: true
        default: 'dashboard'
  # schedule:
  #   - cron: 0 0 * * *
  # push:
  #   branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit
      - name: Run security checks
        run: |
          # safety scan
          # bandit -r .
          # safetu auth