name: Security Checks

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit
      - name: Run security checks
        run: |
          safety scan
          bandit -r votre_projet
          safetu auth