# Generated by Django 5.2.1 on 2025-06-16 21:57

import django.core.validators
import escapevault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="closing_date",
            field=models.CharField(
                blank=True, max_length=5, null=True, validators=[escapevault.models.validate_day_month_format]
            ),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="opening_date",
            field=models.CharField(
                blank=True, max_length=5, null=True, validators=[escapevault.models.validate_day_month_format]
            ),
        ),
    ]
