# Generated by Django 5.2.1 on 2025-06-14 16:48

from django.db import migrations, models

import escapevault.models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="closing_date",
            field=models.CharField(
                blank=True, max_length=5, null=True, validators=[escapevault.models.validate_day_month_format]
            ),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="opening_date",
            field=models.CharField(
                blank=True, max_length=5, null=True, validators=[escapevault.models.validate_day_month_format]
            ),
        ),
    ]
