# Generated by Django 5.2.1 on 2025-06-25 19:53

from django.db import migrations, models

import escapevault.models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0002_alter_nomadeposition_closing_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomadeposition",
            name="link_to_site",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="city",
            field=models.TextField(
                help_text="Nom de la ville",
                max_length=40,
                validators=[escapevault.models.validate_city_format],
            ),
        ),
    ]
