# Generated by Django 5.2.1 on 2025-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0002_alter_nomadeposition_closing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="reviews",
            field=models.TextField(),
        ),
    ]
