# Generated by Django 5.2.1 on 2025-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0003_alter_nomadeposition_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
