# Generated by Django 5.2.1 on 2025-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0003_nomadeposition_link_to_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "Maison"),
                    ("nomade", "Nomade"),
                    ("love", "Coup de cœur"),
                    ("plain", "Ordinaire"),
                    ("ban", "À bannir"),
                ],
                default="plain",
                max_length=100,
            ),
        ),
    ]
