# Generated by Django 5.2.1 on 2025-07-11 16:50

import django.core.validators
import django_countries.fields
import escapevault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0004_alter_nomadeposition_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "Maison"),
                    ("nomade", "Nomade"),
                    ("love", "Coup de coeur"),
                    ("plain", "Ordinaire"),
                    ("ban", "À bannir"),
                ],
                default="plain",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="city",
            field=models.TextField(max_length=40, validators=[escapevault.models.validate_city_format]),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="country",
            field=django_countries.fields.CountryField(
                countries=escapevault.models.NomadePosition.NomadeCountries, default="FR", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="nomadeposition",
            name="stars",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
