# Generated by Django 5.2.1 on 2025-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escapevault", "0004_alter_nomadeposition_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomadeposition",
            name="reviews",
            field=models.JSONField(default=list),
        ),
    ]
